'use client'

import React from 'react'
import { motion } from 'framer-motion'
import CardSwap, { Card } from '@/components/CardSwap'
import { SparklesIcon, BoltIcon, UserGroupIcon, ChartBarIcon } from '@heroicons/react/24/outline'

interface HeroCard {
  id: string
  title: string
  badge: string
  description: string
  gradient: string
  statLabel: string
  statValue: string
  icon: React.ElementType
}

const heroCards: HeroCard[] = [
  {
    id: 'incidents',
    title: 'Live Incident Feed',
    badge: 'Operations Control',
    description: 'Real-time visualization of incident logs with active status indicators.',
    gradient: 'from-[#2563eb] via-[#1d4ed8] to-[#0f172a]',
    statLabel: 'Avg Response',
    statValue: '6m 12s',
    icon: BoltIcon,
  },
  {
    id: 'staff',
    title: 'Staff Readiness',
    badge: 'Staffing & Deployment',
    description: 'Instant visibility into security coverage and position check-ins.',
    gradient: 'from-[#1e293b] via-[#0f172a] to-[#020617]',
    statLabel: 'Coverage',
    statValue: '94%',
    icon: UserGroupIcon,
  },
  {
    id: 'ai',
    title: 'AI Event Summary',
    badge: 'Smart Analytics',
    description: 'Automated post-event reporting generated by our proprietary AI.',
    gradient: 'from-[#be123c] via-[#9f1239] to-[#4c0519]',
    statLabel: 'Confidence',
    statValue: '92%',
    icon: ChartBarIcon,
  },
]

// Animated list item wrapper
const ListItem = ({ children, delay }: { children: React.ReactNode; delay: number }) => (
  <motion.div
    initial={{ opacity: 0, x: -10, y: 5 }}
    animate={{ opacity: 1, x: 0, y: 0 }}
    transition={{ delay, duration: 0.4, ease: "easeOut" }}
  >
    {children}
  </motion.div>
)

function CardVisual({ id }: { id: string }) {
  if (id === 'incidents') {
    return (
      <div className="flex flex-col gap-3 py-2">
        {[
          { label: 'Medical Assist', loc: 'Section 102', time: 'Now', status: 'bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.6)]' },
          { label: 'Crowd Density', loc: 'Gate A', time: '5m', status: 'bg-amber-500 shadow-[0_0_8px_rgba(245,158,11,0.6)]' },
          { label: 'Noise Complaint', loc: 'East Wing', time: '12m', status: 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.6)]' },
        ].map((inc, i) => (
          <ListItem key={i} delay={i * 0.1 + 0.3}>
            <div className="flex items-center gap-3 rounded-lg bg-white/10 p-3 backdrop-blur-md border border-white/10 shadow-sm hover:bg-white/15 transition-colors group">
              <div className="relative flex h-3 w-3 flex-shrink-0">
                <span className={`absolute inline-flex h-full w-full animate-ping rounded-full ${inc.status} opacity-75`}></span>
                <span className={`relative inline-flex h-3 w-3 rounded-full ${inc.status}`}></span>
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex justify-between items-center mb-0.5">
                  <span className="text-xs font-bold text-white truncate group-hover:text-blue-100 transition-colors">{inc.label}</span>
                  <span className="text-[10px] font-mono text-white/60 bg-black/30 px-1.5 py-0.5 rounded border border-white/5 ml-2 flex-shrink-0">
                    {inc.time}
                  </span>
                </div>
                <div className="text-[10px] text-white/70 truncate">{inc.loc}</div>
              </div>
            </div>
          </ListItem>
        ))}
      </div>
    )
  }

  if (id === 'staff') {
    return (
      <div className="flex flex-col justify-center gap-5 py-4">
        {['Security', 'Medical', 'Logistics'].map((role, i) => {
          const percent = [94, 100, 88][i];
          return (
            <ListItem key={i} delay={i * 0.1 + 0.3}>
              <div className="space-y-2">
                <div className="flex justify-between text-[10px] font-bold uppercase tracking-wider text-white/80">
                  <span>{role}</span>
                  <span>{percent}%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-black/30 overflow-hidden backdrop-blur-sm ring-1 ring-white/10">
                  <motion.div 
                    className="h-full rounded-full bg-gradient-to-r from-blue-400 to-cyan-300 shadow-[0_0_10px_rgba(34,211,238,0.5)]" 
                    initial={{ width: 0 }}
                    animate={{ width: `${percent}%` }}
                    transition={{ duration: 1, delay: i * 0.2 + 0.4, ease: "easeOut" }}
                  />
                </div>
              </div>
            </ListItem>
          )
        })}
      </div>
    )
  }

  if (id === 'ai') {
    return (
      <div className="py-2 relative">
        <motion.div 
          className="relative overflow-hidden rounded-xl bg-gradient-to-b from-white/15 to-white/5 p-5 border border-white/10 shadow-inner"
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
        >
          {/* Shimmer Effect Overlay */}
          <div className="absolute inset-0 -translate-x-full animate-[shimmer_2s_infinite] bg-gradient-to-r from-transparent via-white/5 to-transparent" />

          <div className="absolute top-3 right-3">
            <SparklesIcon className="w-5 h-5 text-yellow-300 animate-pulse" />
          </div>
          <div className="space-y-3">
            <div className="flex items-center gap-2 mb-4">
              <div className="h-6 w-6 rounded-full bg-indigo-500 flex items-center justify-center text-[10px] font-bold shadow-lg">AI</div>
              <div className="h-2 w-24 rounded-full bg-white/20 animate-pulse" />
            </div>
            
            {/* Animated Text Lines */}
            {[0.8, 1, 0.7, 0.9].map((width, i) => (
              <motion.div 
                key={i}
                className="h-2 rounded-sm bg-white/30"
                style={{ width: `${width * 100}%` }}
                initial={{ opacity: 0, x: -5 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.1 + 0.4 }}
              />
            ))}
          </div>
          
          <motion.div 
            className="mt-5 flex items-center gap-2"
            initial={{ opacity: 0, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.2 }}
          >
            <div className="flex items-center gap-1.5 rounded-md bg-emerald-500/20 px-2 py-1 border border-emerald-400/30 backdrop-blur-sm">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
              <span className="text-[10px] font-medium text-emerald-100">Analysis Complete</span>
            </div>
          </motion.div>
        </motion.div>
        
        {/* Decorative floating elements */}
        <motion.div 
          className="absolute -right-2 -bottom-2 h-20 w-20 bg-blue-500/30 rounded-full blur-2xl"
          animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.6, 0.3] }}
          transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
        />
      </div>
    )
  }
  return null
}

export default function HeroCards() {
  return (
    <div className="relative w-full max-w-[500px] flex-1 lg:max-w-[540px]">
      <div className="relative mx-auto" style={{ height: 520 }}>
        
        {/* Smoother, Non-flickering Background Glow */}
        <motion.div 
          className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[120%] h-[120%] bg-blue-500/20 blur-[80px] rounded-full -z-10 pointer-events-none"
          animate={{ 
            scale: [1, 1.05, 1],
            opacity: [0.5, 0.7, 0.5]
          }}
          transition={{
            duration: 8,
            repeat: Infinity,
            ease: "easeInOut"
          }}
        />
        
        <div
          className="absolute inset-0 rounded-3xl bg-gradient-to-b from-white/10 to-white/5 shadow-2xl ring-1 ring-white/20 backdrop-blur-sm"
          aria-hidden="true"
        />
        
        <CardSwap
          width={460}
          height={540}
          cardDistance={60}
          verticalDistance={80}
          delay={4500}
          pauseOnHover
        >
          {heroCards.map((card) => (
            <Card key={card.id} className="overflow-hidden rounded-2xl shadow-2xl ring-1 ring-white/10 backdrop-blur-xl">
              <div
                className={`flex h-full w-full flex-col justify-between bg-gradient-to-br ${card.gradient} p-7 text-white relative`}
              >
                {/* Subtle pattern overlay */}
                <div className="absolute inset-0 opacity-10 bg-[radial-gradient(#ffffff33_1px,transparent_1px)] [background-size:16px_16px] pointer-events-none" />

                <div className="relative z-10">
                  <div className="flex justify-between items-start">
                    <div className="inline-flex items-center rounded-md bg-white/15 px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest text-white/90 backdrop-blur-md ring-1 ring-white/20 shadow-sm">
                      {card.badge}
                    </div>
                    <card.icon className="w-6 h-6 text-white/30" />
                  </div>
                  
                  <h3 className="mt-4 text-2xl font-bold tracking-tight text-white drop-shadow-sm">{card.title}</h3>
                  <p className="mt-2 text-sm font-medium text-white/80 leading-relaxed max-w-[90%]">{card.description}</p>
                </div>
                
                <div className="flex-1 flex flex-col justify-center py-2 relative z-10">
                  <CardVisual id={card.id} />
                </div>
                
                <div className="mt-auto pt-4 border-t border-white/10 relative z-10">
                  <div className="flex items-center justify-between">
                    <div className="flex flex-col">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-white/50 mb-0.5">{card.statLabel}</span>
                      <span className="font-mono text-xl font-bold tracking-tight text-white">{card.statValue}</span>
                    </div>
                    <div className="h-8 w-8 rounded-full bg-white/10 flex items-center justify-center ring-1 ring-white/20 backdrop-blur-sm">
                       <svg className="w-4 h-4 text-white/80" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                         <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
                       </svg>
                    </div>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </CardSwap>
      </div>
    </div>
  )
}