export const INCIDENT_EXTRACTION_SYSTEM = 'You extract structured security incident data and ALWAYS return strict JSON. If something is missing, use empty string.';

export const buildIncidentExtractionUser = (incidentTypes: string[], input: string) => `Given these allowed incident types: ${incidentTypes.join(', ')}
Extract the following as strict JSON with keys: incidentType, description, callsign, location, priority, confidence, actionTaken.
- incidentType: One of the allowed incident types only. Key mappings: Fight/violence/assault → "Fight". Medical/illness/injury/ambulance → "Medical". Missing child/person/lost child → "Missing Child/Person". Theft/steal/stolen → "Theft". Eject/remove/escort out → "Ejection". Refuse/deny/entry refused → "Refusal". Fire/smoke/flame → "Fire". Weapon/knife/gun → "Weapon Related". Artist on stage/performing → "Artist On Stage". Artist off stage/finished → "Artist Off Stage". Crowd control/surge → "Crowd Control". Technical/equipment → "Technical". Welfare concern → "Welfare". Suspicious behavior → "Suspicious Behaviour". Lost property → "Lost Property". Site issue → "Site Issue". Environmental/weather → "Environmental". Evacuation → "Evacuation". Fire alarm → "Fire Alarm". Noise complaint → "Noise Complaint". Animal incident → "Animal Incident". Alcohol/drug/drunk → "Alcohol / Drug Related". Sexual misconduct/rape → "Sexual Misconduct". Show stop → "Emergency Show Stop". Showdown/end of show → "Showdown". Timing/schedule → "Event Timing". Attendance/headcount → "Attendance". Accreditation/badge → "Accreditation". Staffing/personnel → "Staffing".
- description: PRESERVE the original incident text as the description. Only fix obvious typos or grammar errors. Keep all original details, callsigns, times, and context. Do NOT simplify or summarize the incident.
- callsign: Extract if present (e.g., A1, R2, Security 1, R1sc, Production Manager). Else empty
- location: Extract ONLY the pure location name and ALWAYS capitalize the first letter of each word (e.g., "Male Toilets", "Main Stage", "North Gate"). For Emergency Show Stop incidents, use "Stage" as the location. Remove ALL callsigns, "by", "reported in", "in the", or any other text. Just the location name with proper capitalization. NEVER generate coordinates or GPS coordinates - only extract location names mentioned in the input.
- priority: One of urgent|high|medium|low based on severity. Rape, sexual assault, serious violence, medical emergencies, fires are "urgent". Missing children/persons, fights, theft, suspicious behavior are "high". Emergency show stops, production issues, stage problems, showdown/end of show events are "medium". Minor incidents and artist events (on/off stage, performing, main act) are "low".
- confidence: 0-1 indicating certainty. Use 0.9+ for clear, unambiguous incidents (like "fight", "medical", "theft", "emergency show stop", "showdown"). Use 0.7-0.8 for less clear cases. Emergency show stops and showdown events are clear incidents and should have high confidence.
- actionTaken: Provide exactly 5 specific actions as a numbered list, plus "Other:" for additional notes. For serious incidents like rape: "1. Secure the area and preserve evidence. 2. Contact police immediately. 3. Provide support to victim. 4. Document all details and witnesses. 5. Coordinate with medical if needed. Other:"

Incident: "${input}"`;


